# Generated by Django 6.0.1 on 2026-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('reporter_name', models.CharField(default='Anonymous', max_length=200)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('scam_content', models.TextField()),
                ('scam_type', models.CharField(choices=[('Phishing', 'Phishing'), ('Fake Payment Request', 'Fake Payment Request'), ('OTP Scam', 'OTP Scam'), ('Romance Scam', 'Romance Scam'), ('Investment Fraud', 'Investment Fraud'), ('Fake Tech Support', 'Fake Tech Support'), ('Malware/Virus', 'Malware/Virus'), ('Lottery Scam', 'Lottery Scam'), ('Banking Fraud', 'Banking Fraud'), ('E-commerce Fraud', 'E-commerce Fraud'), ('Job Offer Scam', 'Job Offer Scam'), ('Credential Harvesting', 'Credential Harvesting'), ('Other', 'Other')], max_length=50)),
                ('platform', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Website', 'Website'), ('Phone Call', 'Phone Call'), ('Social Media', 'Social Media'), ('Other', 'Other')], max_length=50)),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['report_id'], name='analyzer_sc_report__476cb5_idx'), models.Index(fields=['submitted_at'], name='analyzer_sc_submitt_e90adb_idx')],
            },
        ),
    ]
