# Generated by Django 6.0.2 on 2026-02-16 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='analyzer_qu_user_id_3f2a1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='scan',
            name='analyzer_sc_user_id_8a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='analyzer_pa_email_b7ccdd_idx',
            old_name='analyzer_pa_email_9a2b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='analyzer_pa_code_00d7f1_idx',
            old_name='analyzer_pa_code_8c3d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='analyzer_sc_created_b66339_idx',
            old_name='analyzer_sc_created_2c8e0a_idx',
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user_id'], name='analyzer_qu_user_id_c77a44_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['user_id'], name='analyzer_sc_user_id_865454_idx'),
        ),
    ]
